# Generated by Django 5.1.4 on 2025-01-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
